import os

# pull in the parent environment
Import('env')
Import('buildDir')
Import('bm')

# copy environment so that we don't change it
srcEnv = env.Clone()


# --------------------------------------------
#
# We now need to find all the application source files.
# We assume for now that all applications are single .cpp
# files unless they are in a directory with an SConscript
# file. In which case, we defer compilation of the app
# to that SConscript file.
#
# --------------------------------------------

sconsDir = os.getcwd()
os.chdir("%s"%(Dir(".").srcnode().abspath))

# a small "quirk" of scons is that it automatically works out
# which compiler to call. Only trouble with that is that, once we've
# got into a build directory, it kind of forgets, and at the linker stage,
# sees just .o files and thus uses gcc. Using gcc when everything else is c++
# means it doesn't automatically pull in the c++ libraries. Ooops.
#srcEnv.Replace(LINK=srcEnv['CXX'])

# find out where the current SConscript file was.
scfpath = Dir('.').srcnode().abspath


# make sure we link against our library
srcEnv.Append(CPPPATH = ["%s/../src"%(scfpath)] )
srcEnv.Prepend(LIBS = ["MC-core"])
srcEnv.Append(LIBPATH = ["%s/../%s/src"%(scfpath, buildDir)])

# now find the source files.

# find any .cpp files in the current directory.
cpps = [f for f in os.listdir('.') if f[-4:] == '.cpp']


# 1. Get the list of library search directories from the SCons variable.
#    Use .get() to avoid a KeyError if LIBPATH was never explicitly set,
#    though it should be defined by the 'msvc' tool.
LINK_DIRS = env.get('LIBPATH', [])

# 2. Check if the list is empty (for safety)
if LINK_DIRS:
    # 3. Create the list of MSVC-specific /LIBPATH: flags
    #    Iterate over every directory path and prepend the required MSVC syntax.
    msvc_libpath_flags = [f'/LIBPATH:{path}' for path in LINK_DIRS]

    # 4. Clear existing LINKFLAGS and then append the new, correct ones.
    #    Using Replace first ensures no old conflicting flags remain.
    env.Replace(LINKFLAGS=[])
    env.Append(LINKFLAGS=msvc_libpath_flags)

    print("MSVC Linker paths successfully transferred to LINKFLAGS.")


# now search through any subDirectories.
# we are only going to go one level deep.
dirs = [f for f in os.listdir('.') if os.path.isdir(f) ]
for d in dirs:
	dfs = os.listdir(d)
	if "SConscript" in dfs:
		# defer to that file...
		env.SConscript(dirs=[d], variant_dir="%s/apps/%s"%(buildDir,d), exports ='env buildDir bm', duplicate=False)
	else:
		dcpps = ["%s/%s"%(d,f) for f in dfs if f[-4:] == '.cpp']
		cpps = cpps + dcpps

for f in cpps:
	srcf = "%s"%f
	objf = "%s/../%s/bin/%s"%(scfpath , buildDir, f[:-4] )
	targ = srcEnv.Object(objf, srcf)
	srcEnv.Program(targ)


# and go back to whatever directory scons was already in
os.chdir(sconsDir)
